apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 5432
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}
